import type { Patient, Biomarker } from "../../shared/types";

export const patients: Patient[] = [
  {
    id: "1",
    name: "John Doe",
    dateOfBirth: "1985-05-15",
    lastVisit: "2023-10-10",
  },
  {
    id: "2",
    name: "Jack Doe",
    dateOfBirth: "1993-05-15",
    lastVisit: "2025-10-10",
  },
  {
    id: "3",
    name: "Luis Mailey",
    dateOfBirth: "1993-05-15",
    lastVisit: "2025-10-10",
  },
  {
    id: "4",
    name: "Lamine Yamal",
    dateOfBirth: "1985-05-15",
    lastVisit: "2023-10-10",
  },
  {
    id: "5",
    name: "Mbappe",
    dateOfBirth: "1985-05-15",
    lastVisit: "2023-10-10",
  },
];

export const biomarkers: Biomarker[] = [
  {
    id: "b1",
    patientId: "1",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "metabolic",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "normal",
  },
  {
    id: "b2",
    patientId: "2",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "metabolic",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "normal",
  },
  {
    id: "b3",
    patientId: "3",
    name: "Sugar",
    value: 95,
    unit: "mg/dL",
    category: "metabolic",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "normal",
  },
  {
    id: "b4",
    patientId: "2",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "metabolic",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "normal",
  },
  {
    id: "b5",
    patientId: "4",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "metabolic",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "normal",
  },
  {
    id: "b6",
    patientId: "4",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "cardiovascular",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "high",
  },
  {
    id: "b7",
    patientId: "5",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "cardiovascular",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "high",
  },
  {
    id: "b8",
    patientId: "5",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "cardiovascular",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "high",
  },
  {
    id: "b9",
    patientId: "2",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "cardiovascular",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "high",
  },
  {
    id: "b10",
    patientId: "3",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "cardiovascular",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "high",
  },
  {
    id: "b11",
    patientId: "4",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "hormonal",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "low",
  },
  {
    id: "b12",
    patientId: "5",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "hormonal",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "low",
  },
  {
    id: "b13",
    patientId: "3",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "hormonal",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "low",
  },
  {
    id: "b14",
    patientId: "4",
    name: "Glucose",
    value: 95,
    unit: "mg/dL",
    category: "hormonal",
    referenceRange: { min: 70, max: 99 },
    measuredAt: new Date().toISOString(),
    status: "low",
  },
];
